#!/bin/bash
# Railway + Neon Deployment - Command Reference
# Copy and run these commands in order

echo "=========================================="
echo "Railway + Neon Deployment Commands"
echo "=========================================="
echo ""

# Step 1: Build locally
echo "Step 1: Building Spring Boot application..."
echo "Command: mvn clean package -DskipTests"
echo "Expected output: BUILD SUCCESS"
echo ""
echo "Run this and wait for completion"
echo "---"
echo ""

# Step 2: Get Neon connection string
echo "Step 2: Get your Neon database connection string"
echo "1. Go to: https://console.neon.tech"
echo "2. Select your project"
echo "3. Copy the PostgreSQL connection string"
echo "4. It looks like: postgresql://user:password@ep-xxxxx.neon.tech/auctiondeck"
echo ""
echo "Keep this connection string handy - you'll need it in Railway"
echo "---"
echo ""

# Step 3: Push to GitHub
echo "Step 3: Commit and push to GitHub"
echo "Commands:"
echo "  git add ."
echo "  git commit -m 'chore: prepare for Railway + Neon deployment'"
echo "  git push origin main"
echo ""
echo "---"
echo ""

# Step 4: Railway backend deployment
echo "Step 4: Deploy Backend to Railway"
echo "1. Go to: https://railway.app"
echo "2. Sign in with GitHub (create account if needed)"
echo "3. Click 'New Project' → 'Deploy from GitHub repo'"
echo "4. Select your auction repository"
echo "5. Wait for deployment (5-10 minutes)"
echo "6. Copy the generated URL (e.g., https://auction-api.railway.app)"
echo ""
echo "---"
echo ""

# Step 5: Set environment variables
echo "Step 5: Set Environment Variables in Railway Backend"
echo "In Railway Dashboard → Your Backend Service → Variables:"
echo ""
echo "Add these variables:"
echo "  DATABASE_URL = postgresql://user:password@ep-xxxxx.neon.tech/auctiondeck"
echo "  CORS_ORIGINS = http://localhost:4200"
echo "  PORT = 8080"
echo "  LOG_LEVEL = INFO"
echo "  COM_BID_AUCTION_LOG_LEVEL = DEBUG"
echo "  JWT_SECRET = YourSuperSecretKeyHereMustBeAtLeast256BitsLongForHmacSha256!!"
echo "  JWT_EXPIRATION = 86400000"
echo "  JPA_HIBERNATE_DDL_AUTO = validate"
echo "  JPA_SHOW_SQL = false"
echo ""
echo "⚠️ Replace DATABASE_URL with your actual Neon connection string!"
echo "---"
echo ""

# Step 6: Deploy frontend
echo "Step 6: Deploy Frontend to Railway"
echo "1. In Railway Dashboard, click 'New Service'"
echo "2. Choose 'Static Site' (or GitHub repo for Angular)"
echo "3. Configure:"
echo "   - Build Command: npm install && npm run build"
echo "   - Publish Directory: dist/auction"
echo "4. Wait for deployment (3-5 minutes)"
echo "5. Copy the generated URL (e.g., https://auction-web.railway.app)"
echo ""
echo "---"
echo ""

# Step 7: Update CORS
echo "Step 7: Update CORS_ORIGINS in Railway Backend"
echo "Go back to Backend Service → Variables"
echo "Update:"
echo "  CORS_ORIGINS = https://auction-web.railway.app"
echo ""
echo "Railway automatically redeploys when variables change"
echo "---"
echo ""

# Step 8: Test
echo "Step 8: Test Your Application"
echo ""
echo "Test backend API:"
echo "  curl -X GET 'https://auction-api.railway.app/api/health'"
echo ""
echo "Test frontend:"
echo "  Open https://auction-web.railway.app in your browser"
echo ""
echo "Check Network tab in DevTools to verify API calls succeed"
echo ""
echo "---"
echo ""

echo "=========================================="
echo "✅ ALL STEPS COMPLETE!"
echo "=========================================="
echo ""
echo "Your application is now live on Railway with Neon database!"
echo ""
echo "Frontend: https://auction-web.railway.app"
echo "Backend:  https://auction-api.railway.app/api"
echo "Database: Your Neon PostgreSQL instance"
echo ""
echo "For more details, see: RAILWAY_NEON_DEPLOYMENT.md"

